#pragma config(Sensor, in5,    PotPillar,      sensorPotentiometer)
#pragma config(Sensor, in6,    PotPin1,        sensorPotentiometer)
#pragma config(Sensor, in7,    PotPin2,        sensorPotentiometer)
#pragma config(Sensor, in8,    gyroauto,       sensorGyro)
#pragma config(Sensor, dgtl1,  AutoButton1,    sensorTouch)
#pragma config(Sensor, dgtl2,  AutoButton2,    sensorTouch)
#pragma config(Sensor, dgtl3,  ArmButton,      sensorTouch)
#pragma config(Sensor, dgtl4,  Jump1,          sensorDigitalIn)
#pragma config(Motor,  port1,           PincerL,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftfront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightfront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftrear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightrear,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           PillarBottomL, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           PillarBottomR, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           PillarTopL,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           PillarTopR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          PincerR,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
//Hello Chicks!!!

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/
//Variables that are going to be used throughout program
int PillT = 100;
int PillD = -100;
//int degree = 0;
//int error = 100;
int PinOpen = 100;
int PinClose = -100;
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//void potRealign (float potAlign)
//{
	/*	if((SensorValue[in6]) || (SensorValue[in7]) > potAlign)
		{
			motor[PincerR] = 100;
			motor[PincerL] = 100;
		}
		else if ((SensorValue[in6]) || (SensorValue[in7]) < potAlign)
		{
			motor[PincerR] = -100;
			motor[PincerL] = -100;
		}
		else
		{
			motor[PincerL] = 0;
			motor[PincerR] = 0;
		}*/
//}
	/*---------------------------------------------------------------------------*/
	/*                          Pre-Autonomous Functions                         */
	/*                                                                           */
	/*  You may want to perform some actions before the competition starts.      */
	/*  Do them in the following function.  You must return from this function   */
	/*  or the autonomous and usercontrol tasks will not be started.  This       */
	/*  function is only called once after the cortex has been powered on and    */
	/*  not every time that the robot is disabled.                               */
	/*---------------------------------------------------------------------------*/

	void pre_auton()
	{
		//Completely clear out any previous sensor readings by setting the port to "sensorNone"
		SensorType[in8] = sensorNone;
		wait1Msec(1000);
		//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
		SensorType[in8] = gyroauto;
		wait1Msec(2000);
	}

	/*---------------------------------------------------------------------------*/
	/*                                                                           */
	/*                              Autonomous Task                              */
	/*                                                                           */
	/*  This task is used to control your robot during the autonomous phase of   */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/

	task autonomous()   		// Autonomous plan: Drive to fence while raising the 6 bar,
	// get pincers to be parallel with pillars, knock the stars
	// off the fence
	{
		/*
		while(!(SensorValue[dgtl1] == 1 && SensorValue[dgtl2] == 1))
		{
		if (SensorValue[in8] > degree-error && SensorValue[in8]  < degree + error)
		{
		motor[leftfront] = 100;
		motor[rightfront] = 100;
		motor[leftrear] = 100;
		motor[rightrear]= 100;
		}
		else if (SensorValue[in8] < degree-error)
		{
		motor[leftfront] = -50;
		motor[rightfront] = 50;
		motor[leftrear] = -50;
		motor[rightrear]= 50;
		}
		else
		{
		motor[leftfront] = 50;
		motor[rightfront] = -50;
		motor[leftrear] = 50;
		motor[rightrear]= -50;
		}
		*/
		motor[PincerL] = 30;
		motor[PincerR] = 30;
		wait(.75);
		motor[PincerL] = 0;
		motor[PincerR] = 0;
		motor[PillarBottomL] = 100;
		motor[PillarBottomR] = 100;
		motor[PillarTopR] = 100;
		motor[PillarTopL] = 100;
		//untilPotentiometerLessThan(985, in5);
		if(SensorValue[in5] < 985)
		{
			motor[PillarBottomL] = 0;
			motor[PillarBottomR] = 0;
			motor[PillarTopR] = 0;
			motor[PillarTopL] = 0;
		}
		else
		{
			motor[leftfront] = 100;
			motor[rightfront] = 100;
			motor[leftrear] = 100;
			motor[rightrear]= 100;
			wait(3.5);
			motor[leftfront] = -100;
			motor[rightfront] = -100;
			motor[leftrear] = -100;
			motor[rightrear]= -100;
			wait(2.5);
			motor[leftfront] = 0;
			motor[rightfront] = 0;
			motor[leftrear] = 0;
			motor[rightrear]= 0;
		}
	}
//This section is for User control.

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{

			//X-drive code: Controls: Channel 3 is forward and backward,
			//Channel 4: strafes left and right, Channel 1: Turn left/right
			motor[leftfront] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
			motor[rightfront] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
			motor[leftrear] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
			motor[rightrear]= vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];

			//Scoop up/down movement code
			if(vexRT[Btn5U] == 1)
			{
				motor[PillarBottomL] = PillT;
				motor[PillarBottomR] = PillT;
				motor[PillarTopL] = PillT;
				motor[PillarTopR]= PillT;
			}
			else if (vexRT[Btn5D] == 1)
			{
				motor[PillarBottomL] = PillD;
				motor[PillarBottomR] = PillD;
				motor[PillarTopL] = PillD;
				motor[PillarTopR]= PillD;
			}
			else
			{
				motor[PillarBottomL] = 0;
				motor[PillarBottomR] = 0;
				motor[PillarTopL] = 0;
				motor[PillarTopR]= 0;
			}
			if(vexRT[Btn6U] == 1)
		{
			motor[PincerL] = PinOpen;
			motor[PincerR] = PinOpen;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[PincerL] = PinClose;
			motor[PincerR] = PinClose;
		}
		else
		{
			motor[PincerL] = 0;
			motor[PincerR] = 0;
		}
			/*
			if(vexRT[Btn7D] == 1)
			{
				motor[PincerL] = -90;
				untilPotentiometerGreaterThan(3220, PotPin1);
				motor[PincerL] = 0;
			}
			else if(vexRT[Btn7L] == 1)
			{
				motor[PincerL] = 90;
				untilPotentiometerLessThan(1690, PotPin1);
				motor[PincerL] = 0;
			}
			else if(vexRT[Btn7U] == 1)
			{
				motor[PincerR] = 90;
				untilPotentiometerGreaterThan(3000, PotPin2);
				motor[PincerR] = 0;
			}
			else if(vexRT[Btn7R] == 1)
			{
				motor[PincerR] = -90;
				untilPotentiometerLessThan(1800, PotPin2);
				motor[PincerR] = 0;
			}
			*/
		}
	}
