#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  ButtonRight,    sensorTouch)
#pragma config(Sensor, dgtl2,  ButtonLeft,     sensorTouch)
#pragma config(Sensor, dgtl11, jump1,          sensorDigitalIn)
#pragma config(Sensor, dgtl12, jump2,          sensorDigitalIn)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftPillar,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           TopLeftPillarMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftBase,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LeftBottomBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightBase,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RightBottomBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RightPillar,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           TopRightPillarMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
//
//Run with one jumper clip in Digital 12 port.
//

if (SensorValue[dgtl11]==1 && SensorValue[dgtl12] == 0) {
motor[LeftPillar]=127;
motor[RightPillar]=127;		//Makes the star flip over the fence and makes the fliper thing go back to the ground
motor[TopLeftPillarMotor]=127;
motor[TopRightPillarMotor]=127;
wait(.75);
stopMotor(LeftPillar);
stopMotor(RightPillar);
stopMotor(TopRightPillarMotor);
stopMotor(TopLeftPillarMotor);
wait(.5);
motor[LeftBase]=127;
motor[LeftBottomBase]=127;   //Makes Robot go back to the fence then go back a tiny bit
motor[RightBase]=127;
motor[RightBottomBase]=127;
wait(2);
stopMotor(LeftBase);
stopMotor(RightBase);
stopMotor(RightBottomBase);
stopMotor(LeftBottomBase);
wait(.5);
motor[LeftBase]=-127;
motor[LeftBottomBase]=-127;
motor[RightBase]=-127;
motor[RightBottomBase]=-127;
wait(.55);
stopMotor(LeftBase);
stopMotor(RightBase);
stopMotor(RightBottomBase);
stopMotor(LeftBottomBase);
wait(.25);
motor[LeftBase]=127;   			//Turns the robot to face the wall
motor[LeftBottomBase]=127;
motor[RightBase]=-127;
motor[RightBottomBase]=-127;
wait(.5);
stopMotor(LeftBase);
stopMotor(RightBase);
stopMotor(RightBottomBase);
stopMotor(LeftBottomBase);
wait(.25);
motor[LeftBase]=127;
motor[LeftBottomBase]=127;   //Moves the robot to the middle fence
motor[RightBase]=127;
motor[RightBottomBase]=127;
motor[LeftBase]=-127;   			//Turns the robot to face the middle fence
motor[LeftBottomBase]=-127;
motor[RightBase]=127;
motor[RightBottomBase]=127;
wait(.5);
stopMotor(LeftBase);
stopMotor(RightBase);
stopMotor(RightBottomBase);
stopMotor(LeftBottomBase);
motor[LeftPillar]=127;
motor[RightPillar]=127;
motor[TopLeftPillarMotor]=127;
motor[TopRightPillarMotor]=127;
wait(.75);
stopMotor(LeftPillar);
stopMotor(RightPillar);
stopMotor(TopRightPillarMotor);
stopMotor(TopLeftPillarMotor);




/*
motor[LeftBase]=127;				//Pushes the star
motor[LeftBottomBase]=127;
motor[RightBase]=127;
motor[RightBottomBase]=127;
wait(1.5);
stopMotor(LeftBase);
stopMotor(LeftBottomBase);
stopMotor(RightBase);
stopMotor(RightBottomBase);
*/


}
//
//Run with one jumper clip in Digital 11 port.
//
else if (SensorValue[dgtl11]==0 && SensorValue[dgtl12] == 1) {

	wait(3);
}
//
//Run with jumper clips in Digital 11 and Digital 12.
//
else if (SensorValue[dgtl11]==0 && SensorValue[dgtl12] == 0) {

	wait(3);
}
//
//Run code when no jumper clips are present. DEFAULT.
//

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop


while (true)
  {

  motor[RightBase] = vexRT[Ch2];
  motor[LeftBase]  = vexRT[Ch3];
	motor[LeftBottomBase] = vexRT[Ch3];
	motor[RightBottomBase] = vexRT[Ch2];

  if(vexRT[Btn6U]== 1) //Makes the  top motors of the Lift go up
{
	motor[RightPillar] = 100;
	motor[TopRightPillarMotor] = 100;
	motor[LeftPillar] = 100;
	motor[TopLeftPillarMotor]=100;
}
  else if(vexRT[Btn5U]==1) //Makes the bottom motords of the lift go down
  {
  motor[RightPillar] = -100;
	motor[TopRightPillarMotor] = -100;
	motor[LeftPillar]=-100;
	motor[TopLeftPillarMotor]=-100;
}
	else
	{
	motor[RightPillar] = 0;
	motor[TopRightPillarMotor] = 0;
	motor[TopLeftPillarMotor]=0;
	motor[LeftPillar]=0;
	}




}
}
