#pragma config(Sensor, in6,    Pot1,           sensorPotentiometer)
#pragma config(Sensor, in7,    Pot2,           sensorPotentiometer)
#pragma config(Sensor, in8,    gyroauto,       sensorGyro)
#pragma config(Sensor, dgtl1,  AutoButton1,    sensorTouch)
#pragma config(Sensor, dgtl2,  AutoButton2,    sensorTouch)
#pragma config(Sensor, dgtl3,  ArmButton,      sensorTouch)
#pragma config(Motor,  port2,           leftfront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightfront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftrear,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightrear,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           ScoopTop,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ScoopBottom,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           ScoopTop2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ScoopBottom2,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/
//Variables that are going to be used throughout program
int ScoopT = 100;
int ScoopD = -100;
//int degree = 0;
//int error = 100;
int target_value = 1600;
float k = 0.30;
int Pot_error = 0;
float correctionSpeed = 0;
int target_value2 = 1600;
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	//Completely clear out any previous sensor readings by setting the port to "sensorNone"
	SensorType[in8] = sensorNone;
	wait1Msec(1000);
	//Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
	SensorType[in8] = gyroauto;
	wait1Msec(2000);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()   		// Autonomous plan: Drive from wall, go to fence get,
//catapult up straight, then move left and right along wall.
{/*
	while(!(SensorValue[dgtl1] == 1 && SensorValue[dgtl2] == 1))
	{
	if (SensorValue[in8] > degree-error && SensorValue[in8]  < degree + error)
	{
	motor[leftfront] = 100;
	motor[rightfront] = 100;
	motor[leftrear] = 100;
	motor[rightrear]= 100;
	}
	else if (SensorValue[in8] < degree-error)
	{
	motor[leftfront] = -50;
	motor[rightfront] = 50;
	motor[leftrear] = -50;
	motor[rightrear]= 50;
	}
	else
	{
	motor[leftfront] = 50;
	motor[rightfront] = -50;
	motor[leftrear] = 50;
	motor[rightrear]= -50;
	}
	motor[leftfront] = -75;
	motor[rightfront] = -75;
	motor[leftrear] = -75;
	motor[rightrear] = -75;
	wait(0.5);
	motor[leftfront] = 0;
	motor[rightfront] = 0;
	motor[leftrear] = 0;
	motor[rightrear] = 0;

	if(SensorValue[in8] > -900)
	{
	motor[leftfront] = 75;
	motor[rightfront] = -75;
	motor[leftrear] = 75;
	motor[rightrear] = -75;
	}
	if(SensorValue[in8] == -900)
	{
	{
	motor[leftfront] = 75;
	motor[rightfront] = -75;
	motor[leftrear] = 75;
	motor[rightrear] = -75;
	}
	{
	motor[ScoopTop] = ScoopT;
	motor[ScoopTop2] = ScoopT;
	motor[ScoopBottom] = ScoopT;
	motor[ScoopBottom2] = ScoopT;
	wait(1);
	motor[ScoopTop] = ScoopD;
	motor[ScoopTop2] = ScoopD;
	motor[ScoopBottom] = ScoopD;
	motor[ScoopBottom2] = ScoopD;
	wait(1);
	}
	}
	}
	*/
	motor[leftfront] = -100;
	motor[rightfront] = -100;
	motor[leftrear] = -100;
	motor[rightrear]= -100;
	wait(4);
		motor[leftfront] = 0;
	motor[rightfront] = 0;
	motor[leftrear] = 0;
	motor[rightrear]= 0;
	while (true)
			{
			Pot_error = SensorValue[in6] - target_value2 ;
				correctionSpeed = -k * Pot_error;

				motor[ScoopTop] = correctionSpeed;
				motor[ScoopTop2] = correctionSpeed;
				motor[ScoopBottom] = correctionSpeed;
				motor[ScoopBottom2]= correctionSpeed;
}
			}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		//X-drive code: Controls: Channel 3 is forward and backward,
		//Channel 4: strafes left and right, Channel 1: Turn left/right
		motor[leftfront] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		motor[rightfront] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
		motor[leftrear] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
		motor[rightrear]= vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];

		//Scoop up/down movement code
		if(vexRT[Btn6U] == 1)
		{
			motor[ScoopTop] = ScoopT;
			motor[ScoopTop2] = ScoopT;
			motor[ScoopBottom] = ScoopT;
			motor[ScoopBottom2]= ScoopT;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[ScoopTop] = ScoopD;
			motor[ScoopTop2] = ScoopD;
			motor[ScoopBottom] = ScoopD;
			motor[ScoopBottom2]= ScoopD;
		}
		else
		{
			motor[ScoopTop] = 0;
			motor[ScoopBottom] = 0;
			motor[ScoopBottom2] = 0;
			motor[ScoopTop2] = 0;
		}

		//Control loop for holding star slightly off ground
		if (vexRT[Btn7U] == 1)
		{
			wait(0.5);
			while (vexRT[Btn7U] == 0)
			{
				motor[leftfront] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
		motor[rightfront] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
		motor[leftrear] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
		motor[rightrear]= vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];

			Pot_error = SensorValue[in6] - target_value ;
				correctionSpeed = -k * Pot_error;

				motor[ScoopTop] = correctionSpeed;
				motor[ScoopTop2] = correctionSpeed;
				motor[ScoopBottom] = correctionSpeed;
				motor[ScoopBottom2]= correctionSpeed;
			}
			while (!SensorValue[dgtl3])
			{
				motor[ScoopTop] = 127;
				motor[ScoopTop2] = 127;
				motor[ScoopBottom] = 127;
				motor[ScoopBottom2]= 127;
			}

			motor[ScoopTop] = -10;
			motor[ScoopTop2] = -10;
			motor[ScoopBottom] = -10;
			motor[ScoopBottom2]= -10;
			wait(0.5);
		}
	}
}
