#pragma config(Sensor, dgtl1,  bSwitch1,       sensorTouch)
#pragma config(Sensor, dgtl2,  bSwitch2,       sensorTouch)
#pragma config(Sensor, dgtl3,  bSwitch3,       sensorTouch)
#pragma config(Sensor, dgtl4,  cSwitch1,       sensorTouch)
#pragma config(Sensor, dgtl5,  cSwitch2,       sensorTouch)
#pragma config(Sensor, dgtl6,  cSwitch3,       sensorTouch)
#pragma config(Sensor, dgtl8,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           driveMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
SensorValue[encoder] = 0;
turnLEDOff(green);
turnLEDOff(yellow);
turnLEDOff(red);
	while (true)
	{
		if(SensorValue[bSwitch1] == 1)        //Get car to floor one
		{
			if((SensorValue[encoder] >= 0) && (SensorValue[encoder] < 105))
			{
				motor[driveMotor] = 100;
				untilEncoderCounts(52, dgtl11);
				motor[driveMotor] = 0;
			}
			else if(SensorValue[encoder] > 100)
			{
				motor[driveMotor] = -100;
				untilEncoderCounts(100, dgtl11);
				motor[driveMotor] = 0;
			}
			else
			{
				motor[driveMotor] = 0;
				SensorValue[encoder] = 0;
			}
		}
		if (SensorValue[bSwitch2] == 1) //Make sure that the car can go up
		{
			motor[driveMotor] = 100;
		}
		else if(SensorValue[bSwitch3] == 1) //Make sure the car can go down
		{
			motor[driveMotor] = -100;
		}
		else if(SensorValue[cSwitch1] == 1) //Reset encoder
		{
			SensorValue[encoder] = 0;
		}
		else
		{
			motor[driveMotor] = 0;
		}
	}
}
